

print('                                d             ')
print('                                 l            ')
print('                   o            r             ')
print('                    l            o            ')
print('                     l          W             ')
print('                      e                       ')
print('                       H                      ')
print('                 XXXXXXXXXXXXXXXXXXXXXXXXXX   ')
print('                 X                   X     X  ')
print('                 X    JAVA           X     X  ')
print('                 X                   XXXXXX   ')
print('                 X      IS           X        ')
print('                 X                   X        ')
print('                 X                   X        ')
print('                 X      HOT!         X        ')
print('                 X                   X        ')
print('                 X                   X        ')
print('                 X                   X        ')
print('                 XXXXXXXXXXXXXXXXXXXXX        ')
