# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SUbJOPGZnQA7CekqWI38z7PKT6Ntv5K4
"""

precos ={
    "celular": 1500,
    "computador": 5000,
    "tablet": 2500,
}
for item in precos:
  print(item)