import time

def tempo():
    time.sleep(1000) 
print("Diário de um Detento  Racionais MC's")
print("São Paulo, dia 1º de Outubro de 1992, oito horas da manhã")
print("Aqui estou, mais um dia")
print("Sob o olhar sanguinário do vigia")
print("Você não sabe como é caminhar com a cabeça na mira de uma")
print("HK")
print("Metralhadora alemã ou de Israel")
print("Estraçalha ladrão que nem papel")
print("Na muralha, em pé, mais um cidadão José")
print("Servindo o Estado, um PM bom")
print("Passa fome, metido a Charles Bronson")
print("Ele sabe o que eu desejo")
print("Sabe o que eu penso")
print("O dia tá chuvoso, o clima tá tenso")

print("Vários tentaram fugir, eu também quero")
print("Mas de um a cem, a minha chance é zero")
print("Será que Deus ouviu minha oração?")
print("Será que o juiz aceitou a apelação?")
print("Mando um recado lá pro meu irmão")
print("Se tiver usando droga, tá ruim na minha mão")
print("Ele ainda tá com aquela mina")
print("Pode crer, moleque é gente fina")
print("Tirei um dia a menos ou um dia a mais, sei lá")
print("Tanto faz, os dias são iguais")
print("Acendo um cigarro, e vejo o dia passar")

print("Mato o tempo pra ele não me matar")
print("Homem é homem, mulher é mulher")
print("Estuprador é diferente, né?")
print("Toma soco toda hora, ajoelha e beija os pés")
print("E sangra até morrer na rua 10")
print("Cada detento uma mãe, uma crença")
print("Cada crime uma sentença")
print("Cada sentença um motivo, uma história de lágrima")
print("Sangue, vidas inglórias, abandono, miséria, ódio")
print("Sofrimento, desprezo, desilusão, ação do tempo")
print("Misture bem essa química")
print("Pronto, eis um novo detento")

print("Lamentos no corredor, na cela, no pátio")
print("Ao redor do campo, em todos os cantos")
print("Mas eu conheço o sistema, meu irmão, hã")
print("Aqui não tem santo")
print("Rátátátá preciso evitar")
print("Que um safado faça minha mãe chorar")
print("Minha palavra de honra me protege")
print("Pra viver no país das calças bege")
print("Tic, tac, ainda é 9 e 40")
print("O relógio da cadeia anda em câmera lenta")

print("Ratatatá, mais um metrô vai passar")
print("Com gente de bem, apressada, católica")
print("Lendo jornal, satisfeita, hipócrita")
print("Com raiva por dentro, a caminho do centro")
print("Olhando pra cá, curiosos, é lógico")
print("Não, não é não, não é o zoológico")

print("Minha vida não tem tanto valor")
print("Quanto seu celular, seu computador")
print("Hoje tá difícil, não saiu o Sol")
print("Hoje não tem visita, não tem futebol")
print("Alguns companheiros têm a mente mais fraca")
print("Não suportam o tédio, arruma quiaca")
print("Graças a Deus e à Virgem Maria")
print("Faltam só um ano, três meses e uns dias")
print("Tem uma cela lá em cima fechada")
print("Desde Terça-feira ninguém abre pra nada")
print("Só o cheiro de morte e Pinho Sol")
print("Um preso se enforcou com o lençol")

print("Qual que foi? Quem sabe? Não conta")
print("Ia tirar mais uns seis de ponta a ponta")
print("Nada deixa um homem mais doente")
print("Que o abandono dos parentes")
print("Aí moleque, me diz, então, cê quer o quê?")
print("A vaga tá lá esperando você")
print("Pega todos seus artigos importado")
print("Seu currículo no crime e limpa o rabo")
print("A vida bandida é sem futuro")
print("Sua cara fica branca desse lado do muro")
print("Já ouviu falar de Lúcifer?")
print("Que veio do Inferno com moral")
print("Um dia no Carandiru, não, ele é só mais um")
print("Comendo rango azedo com pneumonia")
print("Aqui tem mano de Osasco, do Jardim D'Abril, Parelheiros")
print("Mogi, Jardim Brasil, Bela Vista, Jardim Ângela")
print("Heliópolis, Itapevi, Paraisópolis")

print("Ladrão sangue bom tem moral na quebrada")
print("Mas pro Estado é só um número, mais nada")
print("Nove pavilhões, sete mil homens")
print("Que custam trezentos reais por mês, cada")
print("Na última visita, o neguinho veio aí")
print("Trouxe umas frutas, Marlboro, Free")
print("Ligou que um pilantra lá da área voltou")
print("Com Kadett vermelho, placa de Salvador")
print("Pagando de gatão, ele xinga, ele abusa")
print("Com uma nove milímetros embaixo da blusa")

print("Aí neguinho, vem cá, e os manos onde é que tá?")
print("Lembra desse cururu que tentou me matar?")
print("Aquele puta ganso, pilantra corno manso")
print("Ficava muito doido e deixava a mina só")
print("A mina era virgem e ainda era menor")
print("Agora faz chupeta em troca de pó")
print("Esses papos me incomoda")
print("Se eu tô na rua é foda")
print("É, o mundo roda, ele pode vir pra cá")
print("Não, já, já, meu processo tá aí")
print("Eu quero mudar, eu quero sair")
print("Se eu trombo esse fulano, não tem pá, não tem pum")
print("E eu vou ter que assinar o 121")

print("Amanheceu com Sol, dois de Outubro")
print("Tudo funcionando, limpeza, jumbo")
print("De madrugada eu senti um calafrio")
print("Não era do vento, não era do frio")
print("Acertos de conta tem quase todo dia")
print("Tem outra logo mais, hãn, eu sabia")

print("Lealdade é o que todo preso tenta")
print("Conseguir a paz, de forma violenta")
print("Se um salafrário sacanear alguém")
print("Leva ponto na cara igual Frankestein")
print("Fumaça na janela, tem fogo na cela")
print("Fudeu, foi além, se pã, tem refém")
print("Na maioria, se deixou envolver")
print("Por uns cinco ou seis que não têm nada a perder")
print("Dois ladrões considerados passaram a discutir")
print("Mas não imaginavam o que estaria por vir")
print("Traficantes, homicidas, estelionatários")
print("Uma maioria de moleque primário")
print("Era a brecha que o sistema queria")
print("Avise o IML, chegou o grande dia")
print("Depende do sim ou não de um só homem")
print("Que prefere ser neutro pelo telefone")
print("Ratatatá, caviar e champanhe")

print("Fleury foi almoçar, que se foda a minha mãe")
print("Cachorros assassinos, gás lacrimogêneo")
print("Quem mata mais ladrão ganha medalha de prêmio")
print("O ser humano é descartável no Brasil")
print("Como modess usado ou Bombril")
print("Cadeia? Guarda o que o sistema não quis")
print("Esconde o que a novela não diz")
print("Ratatatá sangue jorra como água")
print("Do ouvido, da boca e nariz")
print("O Senhor é meu pastor")
print("Perdoe o que seu filho fez")
print("Morreu de bruços no Salmo 23")
print("Sem padre, sem repórter")
print("Sem arma, sem socorro")
print("Vai pegar HIV na boca do cachorro")
print("Cadáveres no poço, no pátio interno")
print("Adolf Hitler sorri no inferno")
print("O Robocop do governo é frio, não sente pena")
print("Só ódio e ri como a hiena")
print("Ratatatá, Fleury e sua gangue")
print("Vão nadar numa piscina de sangue")
print("Mas quem vai acreditar no meu depoimento?")
print("Dia 3 de Outubro, diário de um detento")
